// Airline marks served from this site, never hotlinked: the file name for each carrier
// that has one. Carriers absent here fall back to the coloured monogram in AirlineLogo,
// which today is QR, TG, VS, VA, W6.
export const AIRLINE_LOGO_FILES: Record<string, string> = {
  '6E': '6E.svg',
  'AA': 'AA.png',
  'AC': 'AC.png',
  'AF': 'AF.png',
  'AI': 'AI.png',
  'AZ': 'AZ.png',
  'B6': 'B6.svg',
  'BA': 'BA.png',
  'CM': 'CM.svg',
  'CX': 'CX.png',
  'DL': 'DL.svg',
  'EK': 'EK.svg',
  'ET': 'ET.svg',
  'F9': 'F9.png',
  'FR': 'FR.svg',
  'GA': 'GA.svg',
  'HU': 'HU.png',
  'HY': 'HY.png',
  'IB': 'IB.svg',
  'JL': 'JL.svg',
  'KL': 'KL.svg',
  'LH': 'LH.svg',
  'MH': 'MH.svg',
  'NH': 'NH.png',
  'OS': 'OS.png',
  'QF': 'QF.svg',
  'SK': 'SK.svg',
  'SN': 'SN.png',
  'SQ': 'SQ.svg',
  'TK': 'TK.svg',
  'TP': 'TP.svg',
  'U2': 'U2.png',
  'VY': 'VY.png',
  'WN': 'WN.svg',
};
